name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2


    - name: Restore NuGet packages
      run: nuget restore "WinForms SQLite SDB project.sln"

    - name: Build
      run: msbuild /p:Configuration=Release "WinForms SQLite SDB project.sln"

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: Release
        path: bin/Release

